version: "3.1"

services:
  redis:
    image: redis:latest
    command: redis-server --loglevel warning --requirepass 40se02j7
    ports:
      - "6379:6379"
  
  fraxianimeapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 40se02j7
    ports:
      - "8080:8080"
    depends_on:
      - redis
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fraxianimeapp
