APP_PRODUCTION: true
APP_SECRET: ${APP_SECRET}
FRONTEND_URL: https://fraxianime.vercel.app

# Colocar 30 segundos más en CacheScheduler.java (línea 24)
DEFAULT_CACHE_TIME: 30 # Minutos que durará en caché cualquier @Cacheable por defecto:
LAST_CHAPTERS_CACHE_TIME: 48 # Horas que durará en caché los últimos capítulos emitidos

spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}

REDIS_HOST: ${REDIS_HOST}
REDIS_PORT: ${REDIS_PORT}
REDIS_PASSWORD: ${REDIS_PASSWORD}

RAPIDAPI_KEY: ${RAPIDAPI_KEY}

# PROVIDER 1
PROVIDER_JKANIME_URL: https://jkanime.org/
# PROVIDER 2
PROVIDER_ANIMELIFE_URL: https://animelife.net/
# PROVIDER 3 (no usado)
PROVIDER_ANIMEYT_URL: https://animeyt.es/
# PROVIDER 4 (no usado)
PROVIDER_ANIMEFLV_URL: https://animeflv.com.ru/anime/

server:
  port: 8080
