APP_PRODUCTION: true

# PROVIDER 1
PROVIDER_JKANIME_URL: https://jkanime.org/
# PROVIDER 2
PROVIDER_ANIMELIFE_URL: https://animelife.net/
# PROVIDER 3 (no usado)
PROVIDER_ANIMEYT_URL: https://animeyt.es/
# PROVIDER 4 (no usado)
PROVIDER_ANIMEFLV_URL: https://animeflv.com.ru/anime/

server:
  port: 8080
