APP_PRODUCTION: true

REDIS_HOST: ${REDIS_HOST}
REDIS_PASSWORD: ${REDIS_PASSWORD}
REDIS_PORT: ${REDIS_PORT}

# Colocar 30 segundos más en CacheScheduler.java (línea 24)
DEFAULT_CACHE_TIME: 30 # Minutos que durará en caché cualquier @Cacheable por defecto:
LAST_CHAPTERS_CACHE_TIME: 96 # Horas que durará en caché los últimos capítulos emitidos

# PROVIDER 1
PROVIDER_JKANIME_URL: https://jkanime.org/
# PROVIDER 2
PROVIDER_ANIMELIFE_URL: https://animelife.net/
# PROVIDER 3 (no usado)
PROVIDER_ANIMEYT_URL: https://animeyt.es/
# PROVIDER 4 (no usado)
PROVIDER_ANIMEFLV_URL: https://animeflv.com.ru/anime/

server:
  port: 8080
