APP_PRODUCTION: true
FRONTEND_URL1: https://fraxianime.vercel.app
FRONTEND_URL2: https://heatheranime.vercel.app

# Tiempo en caché de los datos
HOME_CACHE_TIME: 30 # Minutos: 'Home'
LAST_CHAPTERS_CACHE_TIME: 7 # Días: 'Home'
DIRECTORY_CACHE_TIME: 7 # Días: 'Directory'
SCHEDULE_CACHE_TIME: 1 # Horas: 'Schedule'
ACTUAL_YEAR_TOP_CACHE_TIME: 7 # Días: 'Top'

spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/${FIREBASE_PROJECT_ID}
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

REDIS_HOST: ${REDIS_HOST}
REDIS_PORT: ${REDIS_PORT}
REDIS_PASSWORD: ${REDIS_PASSWORD}

FIREBASE_WEP_API_KEY: ${FIREBASE_WEP_API_KEY}

RAPIDAPI_KEY: ${RAPIDAPI_KEY}

# PROVIDER 1
PROVIDER_1: https://jkanime.org/
# PROVIDER 2
PROVIDER_2: https://animelife.net/
# PROVIDER 3 (no usado)
PROVIDER_3: https://animeyt.es/
# PROVIDER 4 (no usado)
PROVIDER_4: https://animeflv.com.ru/anime/

server:
  port: 8080
