APP_PRODUCTION: true

PROVEEDOR_JKANIME_URL: https://jkanime.org/

# From Data Chapters
PROVEEDOR_ANIMELIFE_URL: https://animelife.net/
PROVEEDOR_ANIMEYT_URL: https://animeyt.es/
PROVEEDOR_ANIMEFLV_URL: https://animeflv.com.ru/anime/

server:
  port: 8080
